# Generated by Django 5.2.4 on 2025-07-05 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('cancelled_rides_count', models.IntegerField(default=0)),
                ('last_completed_ride_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FareConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_lat', models.FloatField()),
                ('pickup_lng', models.FloatField()),
                ('drop_lat', models.FloatField()),
                ('drop_lng', models.FloatField()),
                ('status', models.CharField(choices=[('create_ride', 'Create Ride'), ('driver_assigned', 'Driver Assigned'), ('driver_at_location', 'Driver at Location'), ('start_ride', 'Ride Started'), ('end_ride', 'Ride Ended')], default='create_ride', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('driver_arrived_at', models.DateTimeField(blank=True, null=True)),
                ('ride_started_at', models.DateTimeField(blank=True, null=True)),
                ('ride_ended_at', models.DateTimeField(blank=True, null=True)),
                ('fare', models.FloatField(blank=True, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uberapp.driver')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uberapp.rider')),
            ],
        ),
    ]
